version: '3'

services:
  db:
    image: postgres
    networks:
      - network
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/tms
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - network
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - db

networks:
  # The presence of these objects is sufficient to define them
  network: 
    external : false