# Generated by Django 4.1 on 2022-09-06 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_length', models.DecimalField(decimal_places=2, max_digits=3)),
                ('movie_starttime', models.TimeField()),
                ('movie_endtime', models.TimeField()),
                ('movie_lang', models.CharField(max_length=100)),
                ('movie_subtitle', models.BooleanField(default=False)),
                ('movie_genre', models.CharField(max_length=200)),
                ('movie_director', models.CharField(max_length=100)),
                ('movie_cast', models.CharField(max_length=250)),
                ('movie_synopsis', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('studio_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('studio_name', models.CharField(max_length=30)),
                ('studio_capacity', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
            ],
        ),
    ]
