# Generated by Django 4.1 on 2022-09-12 10:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_remove_studio_movie_id_showtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.IntegerField(default=1)),
                ('creation_time', models.DateTimeField(default=datetime.datetime(2022, 9, 12, 15, 47, 30, 589717))),
                ('ShowTime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtime', to='movie.showtime')),
            ],
        ),
    ]
